"""Agregar campos imagen y archivos a Noticia

Revision ID: 996795ffe5e0
Revises: 
Create Date: 2024-12-22 00:06:42.398536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996795ffe5e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('_archivos_urls', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.drop_column('_archivos_urls')
        batch_op.drop_column('imagen_url')

    # ### end Alembic commands ###
